/// ドット絵アイコンの絵のデータ。Flutterに依存しない純粋なDartで書き、確認用の
/// 画像出力(tool/render_pixel_icons.dart)からも使えるようにしている。
library;

/// アイコンの種類。
enum PixelIconKind {
  ramen,
  sushi,
  pizza,
  coffee,
  cake,
  beer,
  meat,
  dining,
  tree,
  flower,
  museum,
  ferrisWheel,
  ufoCatcher,
  fish,
  torii,
  onsen,
}

/// アイコン1つの縦横のマス数。
const pixelIconGrid = 12;

/// パターンの文字と色(ARGB)の対応。`.`は透明。電車・駅と同じ配色を使う。
const pixelIconPalette = <String, int>{
  'K': 0xFF2E2923, // 輪郭(電車のink)
  'C': 0xFFF3E6BC, // クリーム
  'c': 0xFFD7C394, // クリームの影
  'F': 0xFFFBF6E6, // 白に近いクリーム
  'G': 0xFF3F6B4C, // 深緑
  'g': 0xFF2D503B, // 深緑の影
  'L': 0xFF7FAE78, // 明るい緑
  'R': 0xFFB23A1E, // ベンガラ色
  'r': 0xFFD9634A, // 明るいベンガラ色
  'B': 0xFF8A5A2E, // 茶
  'b': 0xFF5A3A28, // 濃い茶
  'Y': 0xFFF2C230, // 黄
  'y': 0xFFFFE9A0, // 明るい黄(電車の灯り)
  'O': 0xFFE08A3B, // 橙
  'P': 0xFFF0B3A0, // 桃
  'U': 0xFF3E6E8E, // 青(電車の窓)
  'u': 0xFFA9CFDB, // 明るい青
  'S': 0xFF999C91, // グレー
  'W': 0xFFFFFFFF, // 白
};

/// 各アイコンの絵。1行12文字×12行。
const pixelIconPatterns = <PixelIconKind, List<String>>{
  PixelIconKind.ramen: [
    '....K..K....',
    '...K..K.....',
    '..yyyyyyyy..',
    '.yyGyyyWyyy.',
    'KKKKKKKKKKKK',
    'KRRRRRRRRRRK',
    'KRCCCCCCCCRK',
    '.KRCCCCCCRK.',
    '..KRRRRRRK..',
    '...KKKKKK...',
    '..KK....KK..',
    '............',
  ],
  PixelIconKind.sushi: [
    '............',
    '............',
    '..KKKKKKKK..',
    '.KOOrOOrOOK.',
    'KOOOOOOOOOOK',
    'KFFFFFFFFFFK',
    'KFFFFFFFFFFK',
    '.KFFFFFFFFK.',
    '..KKKKKKKK..',
    '............',
    '............',
    '............',
  ],
  PixelIconKind.pizza: [
    '..KKKKKKKK..',
    '.KOOOOOOOOK.',
    '.KyrryyrryK.',
    '..KyyyrryK..',
    '..KyrryyyK..',
    '...KyyyrK...',
    '...KyrryK...',
    '....KyyK....',
    '....KrrK....',
    '.....KK.....',
    '............',
    '............',
  ],
  PixelIconKind.coffee: [
    '...K..K.....',
    '....K..K....',
    '...K..K.....',
    '............',
    '.KKKKKKKK...',
    '.KBBBBBBKKK.',
    '.KCCCCCCK.K.',
    '.KCCCCCCK.K.',
    '..KCCCCCKKK.',
    '..KKKKKKK...',
    '.KKKKKKKKK..',
    '............',
  ],
  PixelIconKind.cake: [
    '......R.....',
    '.....RRR....',
    '....KKKKK...',
    '..KKPPPPPKK.',
    '.KPPPPPPPPPK',
    'KKKKKKKKKKKK',
    'KCCCCCCCCCCK',
    'KRRRRRRRRRRK',
    'KCCCCCCCCCCK',
    'KKKKKKKKKKKK',
    '............',
    '............',
  ],
  PixelIconKind.beer: [
    '..FF.FF.....',
    '.FFFFFFFF...',
    '.KKKKKKKK...',
    '.KYyYYyYYK..',
    '.KYYYYYYYKKK',
    '.KYyYYyYYK.K',
    '.KYYYYYYYK.K',
    '.KYyYYyYYKKK',
    '.KYYYYYYYK..',
    '.KKKKKKKKK..',
    '............',
    '............',
  ],
  PixelIconKind.meat: [
    '............',
    '..KKKKKKK...',
    '.KRRRRRRRK..',
    'KRRrRRCCRRK.',
    'KRRRRRCCRRRK',
    'KRRRrRRRRRRK',
    '.KRRRRRRRRK.',
    '..KRRRRRRK..',
    '...KKKKKK...',
    '............',
    '............',
    '............',
  ],
  PixelIconKind.dining: [
    '.K.K.K..KK..',
    '.K.K.K..KKK.',
    '.K.K.K..KKK.',
    '.KKKKK..KKK.',
    '..KKK...KKK.',
    '...K....KK..',
    '...K....KK..',
    '...K....KK..',
    '...K....KK..',
    '...K....KK..',
    '...K....KK..',
    '............',
  ],
  PixelIconKind.tree: [
    '....gggg....',
    '..gLLLLLLg..',
    '.gLLLLLLLLg.',
    '.gLLgLLLLLg.',
    '.gLLLLLLgLg.',
    '..gLLLLLLg..',
    '...gggggg...',
    '......BB....',
    '......BB....',
    '......BB....',
    '....bbBBbb..',
    '............',
  ],
  PixelIconKind.flower: [
    '............',
    '...PP..PP...',
    '..PPPPPPPP..',
    '..PPPYYPPP..',
    '..PPPYYPPP..',
    '..PPPPPPPP..',
    '...PP..PP...',
    '.....GG.....',
    '.....GG.....',
    '..LL.GG.LL..',
    '...LLGGLL...',
    '.....GG.....',
  ],
  PixelIconKind.museum: [
    '.....KK.....',
    '...KKCCKK...',
    '.KKCCCCCCKK.',
    'KKKKKKKKKKKK',
    '.KCKCKCKCKC.',
    '.KCKCKCKCKC.',
    '.KCKCKCKCKC.',
    '.KCKCKCKCKC.',
    'KKKKKKKKKKKK',
    'KccccccccccK',
    'KKKKKKKKKKKK',
    '............',
  ],
  PixelIconKind.ferrisWheel: [
    '...KKRKKK...',
    '.KK..KK..KK.',
    '.R...KK...Y.',
    'K....KK....K',
    'KKKKKKKKKKKK',
    'K....KK....K',
    '.Y...KK...R.',
    '.KK..KK..KK.',
    '...KKKKKK...',
    '....K..K....',
    '...K....K...',
    '..KKKKKKKK..',
  ],
  PixelIconKind.ufoCatcher: [
    'KKKKKKKKKKKK',
    'KRRRRRRRRRRK',
    'KKKKKKKKKKKK',
    'KuuuuKKuuuuK',
    'KuuuuKKuuuuK',
    'KuuuKKKKuuuK',
    'KuuKKuuKKuuK',
    'KuuuuuuuuuuK',
    'KuuuPPPPuuuK',
    'KuuPPPPPPuuK',
    'KKKKKKKKKKKK',
    '.KK......KK.',
  ],
  PixelIconKind.fish: [
    '............',
    '............',
    '...KKKKK..K.',
    '..KUUUUUKKK.',
    '.KUUWKUUUUKK',
    '.KUUUUUUUKKK',
    '..KUUUUUKKK.',
    '...KKKKK..K.',
    '............',
    '............',
    '............',
    '............',
  ],
  PixelIconKind.torii: [
    'KKKKKKKKKKKK',
    'RRRRRRRRRRRR',
    '.KRRRRRRRRK.',
    '..R......R..',
    '.RRRRRRRRRR.',
    '..R......R..',
    '..R......R..',
    '..R......R..',
    '..R......R..',
    '.KK......KK.',
    '............',
    '............',
  ],
  PixelIconKind.onsen: [
    '..K..K..K...',
    '...K..K..K..',
    '..K..K..K...',
    '............',
    '.UUUUUUUUUU.',
    'UuuUuuUuuUuU',
    'UUUUUUUUUUUU',
    'KUUUUUUUUUUK',
    '.KKKKKKKKKK.',
    '............',
    '............',
    '............',
  ],
};
